Feature/27376
prefeiturasp/SME-Aplicativo-Aluno-API pull request #312
Opened 2020-11-12 19:01 UTC by CarlosDias-amcom

2020-11-12 19:29 UTC, rgalante82 commented on src/SME.AE.Aplicacao/Comum/Interfaces/Repositorios/ITurmaRepositorio.cs
> +        Task<TurmaModalidadeDeEnsinoDto> ObterModalidadeDeEnsinoAsync(string codigoTurma);
evita usar o sufixo Async, nomes de métodos não devem conter informações sobre tipos apenas representar de forma clara sua ação.

2020-11-12 19:35 UTC, rgalante82 approved these changes

2020-11-12 20:09 UTC, rgalante82 requested changes
incluir na tabela de parametros

2020-11-12 20:09 UTC, rgalante82 commented on scripts/V35__Inclusao_Registros_Frequencia_Aluno_Cor.sql
> +delete from frequencia_aluno_cor;
manter essas informações na tabela de parâmetros

2020-11-13 01:33 UTC, CarlosDias-amcom commented on src/SME.AE.Aplicacao/Comum/Interfaces/Repositorios/ITurmaRepositorio.cs
> +        Task<TurmaModalidadeDeEnsinoDto> ObterModalidadeDeEnsinoAsync(string codigoTurma);
Feito

2020-11-13 01:33 UTC, CarlosDias-amcom commented on scripts/V35__Inclusao_Registros_Frequencia_Aluno_Cor.sql
> +delete from frequencia_aluno_cor;
Feito

2020-11-13 11:49 UTC, ivanomucciamcom approved these changes

2020-11-13 12:02 UTC, rgalante82 approved these changes

2020-11-13 12:03 UTC, merged